name: build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=debug ..
    - name: build
      run: cmake --build build
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: build
      run: cmake --build build
